//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionWeb.ServiceUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetlistId", ReplyAction="http://tempuri.org/IService1/GetlistIdResponse")]
        BE.UsuarioModel GetlistId(int IdUsusario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetlistId", ReplyAction="http://tempuri.org/IService1/GetlistIdResponse")]
        System.Threading.Tasks.Task<BE.UsuarioModel> GetlistIdAsync(int IdUsusario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setInsertUs", ReplyAction="http://tempuri.org/IService1/setInsertUsResponse")]
        string setInsertUs(BE.UsuarioModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setInsertUs", ReplyAction="http://tempuri.org/IService1/setInsertUsResponse")]
        System.Threading.Tasks.Task<string> setInsertUsAsync(BE.UsuarioModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUpdateUs", ReplyAction="http://tempuri.org/IService1/setUpdateUsResponse")]
        void setUpdateUs(BE.UsuarioModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUpdateUs", ReplyAction="http://tempuri.org/IService1/setUpdateUsResponse")]
        System.Threading.Tasks.Task setUpdateUsAsync(BE.UsuarioModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setDeleteUs", ReplyAction="http://tempuri.org/IService1/setDeleteUsResponse")]
        void setDeleteUs(BE.UsuarioModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setDeleteUs", ReplyAction="http://tempuri.org/IService1/setDeleteUsResponse")]
        System.Threading.Tasks.Task setDeleteUsAsync(BE.UsuarioModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuarioAll", ReplyAction="http://tempuri.org/IService1/getUsuarioAllResponse")]
        BE.UsuarioModel[] getUsuarioAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuarioAll", ReplyAction="http://tempuri.org/IService1/getUsuarioAllResponse")]
        System.Threading.Tasks.Task<BE.UsuarioModel[]> getUsuarioAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PresentacionWeb.ServiceUsuario.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PresentacionWeb.ServiceUsuario.IService1>, PresentacionWeb.ServiceUsuario.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BE.UsuarioModel GetlistId(int IdUsusario) {
            return base.Channel.GetlistId(IdUsusario);
        }
        
        public System.Threading.Tasks.Task<BE.UsuarioModel> GetlistIdAsync(int IdUsusario) {
            return base.Channel.GetlistIdAsync(IdUsusario);
        }
        
        public string setInsertUs(BE.UsuarioModel obj) {
            return base.Channel.setInsertUs(obj);
        }
        
        public System.Threading.Tasks.Task<string> setInsertUsAsync(BE.UsuarioModel obj) {
            return base.Channel.setInsertUsAsync(obj);
        }
        
        public void setUpdateUs(BE.UsuarioModel obj) {
            base.Channel.setUpdateUs(obj);
        }
        
        public System.Threading.Tasks.Task setUpdateUsAsync(BE.UsuarioModel obj) {
            return base.Channel.setUpdateUsAsync(obj);
        }
        
        public void setDeleteUs(BE.UsuarioModel obj) {
            base.Channel.setDeleteUs(obj);
        }
        
        public System.Threading.Tasks.Task setDeleteUsAsync(BE.UsuarioModel obj) {
            return base.Channel.setDeleteUsAsync(obj);
        }
        
        public BE.UsuarioModel[] getUsuarioAll() {
            return base.Channel.getUsuarioAll();
        }
        
        public System.Threading.Tasks.Task<BE.UsuarioModel[]> getUsuarioAllAsync() {
            return base.Channel.getUsuarioAllAsync();
        }
    }
}
